import type { RecipeDetail, RecipeDifficulty, RecipeSource } from './types';

/**
 * Seeded recipe catalog for mock mode and initial system recipes.
 * Each recipe includes full detail (ingredients + steps).
 */
export const SEED_RECIPES: RecipeDetail[] = [
  {
    id: 'seed-001',
    userId: null,
    title: 'Creamy Spinach Pasta',
    description: 'A quick and comforting pasta with fresh spinach in a creamy sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80',
    cookTimeMinutes: 15,
    prepTimeMinutes: 5,
    servings: 2,
    difficulty: 'easy' as RecipeDifficulty,
    tags: ['pasta', 'vegetarian', 'quick', 'dinner'],
    visibility: 'private',
    source: 'system' as RecipeSource,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    deleted: false,
    ingredients: [
      { id: 'si-001', recipeId: 'seed-001', name: 'Spinach', normalizedName: 'spinach', quantity: 200, unit: 'g', optional: false, sortOrder: 0 },
      { id: 'si-002', recipeId: 'seed-001', name: 'Pasta', normalizedName: 'pasta', quantity: 250, unit: 'g', optional: false, sortOrder: 1 },
      { id: 'si-003', recipeId: 'seed-001', name: 'Heavy Cream', normalizedName: 'heavy cream', quantity: 200, unit: 'ml', optional: false, sortOrder: 2 },
      { id: 'si-004', recipeId: 'seed-001', name: 'Garlic', normalizedName: 'garlic', quantity: 3, unit: 'pieces', optional: false, sortOrder: 3 },
      { id: 'si-005', recipeId: 'seed-001', name: 'Parmesan Cheese', normalizedName: 'parmesan cheese', quantity: 50, unit: 'g', optional: false, sortOrder: 4 },
      { id: 'si-006', recipeId: 'seed-001', name: 'Red Pepper Flakes', normalizedName: 'red pepper flakes', optional: true, sortOrder: 5 },
    ],
    steps: [
      { id: 'ss-001', recipeId: 'seed-001', stepNumber: 1, instruction: 'Cook pasta according to package directions. Reserve 1/2 cup pasta water before draining.', estimatedMinutes: 10 },
      { id: 'ss-002', recipeId: 'seed-001', stepNumber: 2, instruction: 'While pasta cooks, mince garlic and sauté in olive oil over medium heat until fragrant, about 1 minute.', estimatedMinutes: 2 },
      { id: 'ss-003', recipeId: 'seed-001', stepNumber: 3, instruction: 'Add spinach and cook until wilted, about 2 minutes.', estimatedMinutes: 2 },
      { id: 'ss-004', recipeId: 'seed-001', stepNumber: 4, instruction: 'Pour in cream, add parmesan, and stir until sauce thickens slightly.', estimatedMinutes: 2 },
      { id: 'ss-005', recipeId: 'seed-001', stepNumber: 5, instruction: 'Toss in drained pasta. Add pasta water as needed for desired consistency. Season and serve.', estimatedMinutes: 1 },
    ],
  },
  {
    id: 'seed-002',
    userId: null,
    title: 'Chicken Stir Fry',
    description: 'Colorful vegetable stir fry with tender chicken in a savory sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80',
    cookTimeMinutes: 25,
    prepTimeMinutes: 10,
    servings: 3,
    difficulty: 'medium' as RecipeDifficulty,
    tags: ['asian', 'dinner', 'protein', 'stir fry'],
    visibility: 'private',
    source: 'system' as RecipeSource,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    deleted: false,
    ingredients: [
      { id: 'si-010', recipeId: 'seed-002', name: 'Chicken Breast', normalizedName: 'chicken breast', quantity: 400, unit: 'g', optional: false, sortOrder: 0 },
      { id: 'si-011', recipeId: 'seed-002', name: 'Bell Peppers', normalizedName: 'bell pepper', quantity: 2, unit: 'pieces', optional: false, sortOrder: 1 },
      { id: 'si-012', recipeId: 'seed-002', name: 'Soy Sauce', normalizedName: 'soy sauce', quantity: 3, unit: 'tbsp', optional: false, sortOrder: 2 },
      { id: 'si-013', recipeId: 'seed-002', name: 'Ginger', normalizedName: 'ginger', quantity: 1, unit: 'tbsp', optional: false, sortOrder: 3 },
      { id: 'si-014', recipeId: 'seed-002', name: 'Garlic', normalizedName: 'garlic', quantity: 3, unit: 'pieces', optional: false, sortOrder: 4 },
      { id: 'si-015', recipeId: 'seed-002', name: 'Broccoli', normalizedName: 'broccoli', quantity: 200, unit: 'g', optional: false, sortOrder: 5 },
      { id: 'si-016', recipeId: 'seed-002', name: 'Sesame Seeds', normalizedName: 'sesame seeds', optional: true, sortOrder: 6 },
    ],
    steps: [
      { id: 'ss-010', recipeId: 'seed-002', stepNumber: 1, instruction: 'Cut chicken breast into thin strips. Season with salt and pepper.', estimatedMinutes: 5 },
      { id: 'ss-011', recipeId: 'seed-002', stepNumber: 2, instruction: 'Heat oil in a wok or large skillet over high heat. Sear chicken until golden, about 4 minutes. Remove and set aside.', estimatedMinutes: 5 },
      { id: 'ss-012', recipeId: 'seed-002', stepNumber: 3, instruction: 'In the same wok, stir-fry bell peppers and broccoli for 3 minutes until crisp-tender.', estimatedMinutes: 3 },
      { id: 'ss-013', recipeId: 'seed-002', stepNumber: 4, instruction: 'Add minced garlic and grated ginger. Cook for 30 seconds until fragrant.', estimatedMinutes: 1 },
      { id: 'ss-014', recipeId: 'seed-002', stepNumber: 5, instruction: 'Return chicken to wok. Add soy sauce and toss everything together. Cook 2 more minutes.', estimatedMinutes: 3 },
      { id: 'ss-015', recipeId: 'seed-002', stepNumber: 6, instruction: 'Garnish with sesame seeds and serve over steamed rice.', estimatedMinutes: 1 },
    ],
  },
  {
    id: 'seed-003',
    userId: null,
    title: 'Spicy Chickpea Curry',
    description: 'Hearty and warming chickpea curry with aromatic spices and coconut milk.',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
    cookTimeMinutes: 40,
    prepTimeMinutes: 10,
    servings: 4,
    difficulty: 'medium' as RecipeDifficulty,
    tags: ['curry', 'vegetarian', 'vegan', 'dinner', 'spicy'],
    visibility: 'private',
    source: 'system' as RecipeSource,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    deleted: false,
    ingredients: [
      { id: 'si-020', recipeId: 'seed-003', name: 'Chickpeas', normalizedName: 'chickpea', quantity: 400, unit: 'g', optional: false, sortOrder: 0 },
      { id: 'si-021', recipeId: 'seed-003', name: 'Coconut Milk', normalizedName: 'coconut milk', quantity: 400, unit: 'ml', optional: false, sortOrder: 1 },
      { id: 'si-022', recipeId: 'seed-003', name: 'Onion', normalizedName: 'onion', quantity: 1, unit: 'pieces', optional: false, sortOrder: 2 },
      { id: 'si-023', recipeId: 'seed-003', name: 'Garlic', normalizedName: 'garlic', quantity: 4, unit: 'pieces', optional: false, sortOrder: 3 },
      { id: 'si-024', recipeId: 'seed-003', name: 'Tomatoes', normalizedName: 'tomato', quantity: 3, unit: 'pieces', optional: false, sortOrder: 4 },
      { id: 'si-025', recipeId: 'seed-003', name: 'Curry Powder', normalizedName: 'curry powder', quantity: 2, unit: 'tbsp', optional: false, sortOrder: 5 },
      { id: 'si-026', recipeId: 'seed-003', name: 'Cumin', normalizedName: 'cumin', quantity: 1, unit: 'tsp', optional: false, sortOrder: 6 },
      { id: 'si-027', recipeId: 'seed-003', name: 'Fresh Cilantro', normalizedName: 'cilantro', optional: true, sortOrder: 7 },
    ],
    steps: [
      { id: 'ss-020', recipeId: 'seed-003', stepNumber: 1, instruction: 'Dice onion and mince garlic. Chop tomatoes into chunks.', estimatedMinutes: 5 },
      { id: 'ss-021', recipeId: 'seed-003', stepNumber: 2, instruction: 'Heat oil in a large pot over medium heat. Sauté onion until soft, about 5 minutes.', estimatedMinutes: 5 },
      { id: 'ss-022', recipeId: 'seed-003', stepNumber: 3, instruction: 'Add garlic, curry powder, and cumin. Stir for 1 minute until fragrant.', estimatedMinutes: 1 },
      { id: 'ss-023', recipeId: 'seed-003', stepNumber: 4, instruction: 'Add chopped tomatoes and cook for 5 minutes until they break down.', estimatedMinutes: 5 },
      { id: 'ss-024', recipeId: 'seed-003', stepNumber: 5, instruction: 'Add chickpeas and coconut milk. Bring to a simmer and cook for 20 minutes.', estimatedMinutes: 20 },
      { id: 'ss-025', recipeId: 'seed-003', stepNumber: 6, instruction: 'Season with salt and pepper. Garnish with fresh cilantro and serve with rice.', estimatedMinutes: 2 },
    ],
  },
  {
    id: 'seed-004',
    userId: null,
    title: 'Simple Egg Fried Rice',
    description: 'Classic fried rice with eggs and vegetables — perfect for using up leftover rice.',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80',
    cookTimeMinutes: 10,
    prepTimeMinutes: 5,
    servings: 2,
    difficulty: 'easy' as RecipeDifficulty,
    tags: ['asian', 'quick', 'dinner', 'lunch', 'one pot'],
    visibility: 'private',
    source: 'system' as RecipeSource,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    deleted: false,
    ingredients: [
      { id: 'si-030', recipeId: 'seed-004', name: 'Cooked Rice', normalizedName: 'rice', quantity: 400, unit: 'g', optional: false, sortOrder: 0 },
      { id: 'si-031', recipeId: 'seed-004', name: 'Eggs', normalizedName: 'egg', quantity: 3, unit: 'pieces', optional: false, sortOrder: 1 },
      { id: 'si-032', recipeId: 'seed-004', name: 'Green Onion', normalizedName: 'green onion', quantity: 3, unit: 'pieces', optional: false, sortOrder: 2 },
      { id: 'si-033', recipeId: 'seed-004', name: 'Soy Sauce', normalizedName: 'soy sauce', quantity: 2, unit: 'tbsp', optional: false, sortOrder: 3 },
      { id: 'si-034', recipeId: 'seed-004', name: 'Sesame Oil', normalizedName: 'sesame oil', quantity: 1, unit: 'tsp', optional: true, sortOrder: 4 },
      { id: 'si-035', recipeId: 'seed-004', name: 'Frozen Peas', normalizedName: 'pea', quantity: 100, unit: 'g', optional: true, sortOrder: 5 },
    ],
    steps: [
      { id: 'ss-030', recipeId: 'seed-004', stepNumber: 1, instruction: 'Beat eggs in a bowl. Slice green onions.', estimatedMinutes: 2 },
      { id: 'ss-031', recipeId: 'seed-004', stepNumber: 2, instruction: 'Heat oil in a wok over high heat. Scramble eggs and break into small pieces. Remove.', estimatedMinutes: 2 },
      { id: 'ss-032', recipeId: 'seed-004', stepNumber: 3, instruction: 'Add rice to the wok and stir-fry for 3 minutes until slightly crispy.', estimatedMinutes: 3 },
      { id: 'ss-033', recipeId: 'seed-004', stepNumber: 4, instruction: 'Add soy sauce, return eggs, add green onions and peas. Toss to combine. Drizzle sesame oil.', estimatedMinutes: 2 },
    ],
  },
  {
    id: 'seed-005',
    userId: null,
    title: 'Tomato Basil Soup',
    description: 'Comforting homemade tomato soup with fresh basil — perfect for using up ripe tomatoes.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80',
    cookTimeMinutes: 30,
    prepTimeMinutes: 10,
    servings: 4,
    difficulty: 'easy' as RecipeDifficulty,
    tags: ['soup', 'vegetarian', 'comfort food', 'lunch'],
    visibility: 'private',
    source: 'system' as RecipeSource,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    deleted: false,
    ingredients: [
      { id: 'si-040', recipeId: 'seed-005', name: 'Tomatoes', normalizedName: 'tomato', quantity: 6, unit: 'pieces', optional: false, sortOrder: 0 },
      { id: 'si-041', recipeId: 'seed-005', name: 'Onion', normalizedName: 'onion', quantity: 1, unit: 'pieces', optional: false, sortOrder: 1 },
      { id: 'si-042', recipeId: 'seed-005', name: 'Garlic', normalizedName: 'garlic', quantity: 3, unit: 'pieces', optional: false, sortOrder: 2 },
      { id: 'si-043', recipeId: 'seed-005', name: 'Fresh Basil', normalizedName: 'basil', quantity: 20, unit: 'g', optional: false, sortOrder: 3 },
      { id: 'si-044', recipeId: 'seed-005', name: 'Vegetable Broth', normalizedName: 'vegetable broth', quantity: 500, unit: 'ml', optional: false, sortOrder: 4 },
      { id: 'si-045', recipeId: 'seed-005', name: 'Heavy Cream', normalizedName: 'heavy cream', quantity: 100, unit: 'ml', optional: true, sortOrder: 5 },
    ],
    steps: [
      { id: 'ss-040', recipeId: 'seed-005', stepNumber: 1, instruction: 'Dice onion and mince garlic. Roughly chop tomatoes.', estimatedMinutes: 5 },
      { id: 'ss-041', recipeId: 'seed-005', stepNumber: 2, instruction: 'Sauté onion in olive oil until soft. Add garlic and cook 1 minute.', estimatedMinutes: 6 },
      { id: 'ss-042', recipeId: 'seed-005', stepNumber: 3, instruction: 'Add tomatoes and broth. Bring to a boil, then reduce to simmer for 15 minutes.', estimatedMinutes: 16 },
      { id: 'ss-043', recipeId: 'seed-005', stepNumber: 4, instruction: 'Blend until smooth with an immersion blender. Stir in cream if using. Add torn basil.', estimatedMinutes: 3 },
    ],
  },
  {
    id: 'seed-006',
    userId: null,
    title: 'Quick Banana Pancakes',
    description: 'Fluffy pancakes with ripe bananas — great for using up overripe bananas.',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80',
    cookTimeMinutes: 15,
    prepTimeMinutes: 5,
    servings: 2,
    difficulty: 'easy' as RecipeDifficulty,
    tags: ['breakfast', 'sweet', 'quick', 'vegetarian'],
    visibility: 'private',
    source: 'system' as RecipeSource,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    deleted: false,
    ingredients: [
      { id: 'si-050', recipeId: 'seed-006', name: 'Ripe Bananas', normalizedName: 'banana', quantity: 2, unit: 'pieces', optional: false, sortOrder: 0 },
      { id: 'si-051', recipeId: 'seed-006', name: 'Eggs', normalizedName: 'egg', quantity: 2, unit: 'pieces', optional: false, sortOrder: 1 },
      { id: 'si-052', recipeId: 'seed-006', name: 'Flour', normalizedName: 'flour', quantity: 100, unit: 'g', optional: false, sortOrder: 2 },
      { id: 'si-053', recipeId: 'seed-006', name: 'Milk', normalizedName: 'milk', quantity: 100, unit: 'ml', optional: false, sortOrder: 3 },
      { id: 'si-054', recipeId: 'seed-006', name: 'Honey', normalizedName: 'honey', optional: true, sortOrder: 4 },
      { id: 'si-055', recipeId: 'seed-006', name: 'Cinnamon', normalizedName: 'cinnamon', optional: true, sortOrder: 5 },
    ],
    steps: [
      { id: 'ss-050', recipeId: 'seed-006', stepNumber: 1, instruction: 'Mash bananas in a bowl. Whisk in eggs and milk until smooth.', estimatedMinutes: 3 },
      { id: 'ss-051', recipeId: 'seed-006', stepNumber: 2, instruction: 'Add flour and mix until just combined. Do not over-mix.', estimatedMinutes: 2 },
      { id: 'ss-052', recipeId: 'seed-006', stepNumber: 3, instruction: 'Heat a non-stick pan over medium heat. Pour small circles of batter.', estimatedMinutes: 1 },
      { id: 'ss-053', recipeId: 'seed-006', stepNumber: 4, instruction: 'Cook until bubbles form on surface, about 2 minutes. Flip and cook 1 more minute.', estimatedMinutes: 8 },
      { id: 'ss-054', recipeId: 'seed-006', stepNumber: 5, instruction: 'Serve with honey and cinnamon if desired.', estimatedMinutes: 1 },
    ],
  },
  {
    id: 'seed-007',
    userId: null,
    title: 'Garlic Butter Shrimp',
    description: 'Succulent shrimp in a rich garlic butter sauce — ready in minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?w=600&q=80',
    cookTimeMinutes: 10,
    prepTimeMinutes: 5,
    servings: 2,
    difficulty: 'easy' as RecipeDifficulty,
    tags: ['seafood', 'quick', 'dinner', 'protein'],
    visibility: 'private',
    source: 'system' as RecipeSource,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    deleted: false,
    ingredients: [
      { id: 'si-060', recipeId: 'seed-007', name: 'Shrimp', normalizedName: 'shrimp', quantity: 400, unit: 'g', optional: false, sortOrder: 0 },
      { id: 'si-061', recipeId: 'seed-007', name: 'Butter', normalizedName: 'butter', quantity: 50, unit: 'g', optional: false, sortOrder: 1 },
      { id: 'si-062', recipeId: 'seed-007', name: 'Garlic', normalizedName: 'garlic', quantity: 5, unit: 'pieces', optional: false, sortOrder: 2 },
      { id: 'si-063', recipeId: 'seed-007', name: 'Lemon', normalizedName: 'lemon', quantity: 1, unit: 'pieces', optional: false, sortOrder: 3 },
      { id: 'si-064', recipeId: 'seed-007', name: 'Parsley', normalizedName: 'parsley', optional: true, sortOrder: 4 },
    ],
    steps: [
      { id: 'ss-060', recipeId: 'seed-007', stepNumber: 1, instruction: 'Peel and devein shrimp if needed. Pat dry with paper towels.', estimatedMinutes: 3 },
      { id: 'ss-061', recipeId: 'seed-007', stepNumber: 2, instruction: 'Melt butter in a large skillet over medium-high heat. Add minced garlic and cook 30 seconds.', estimatedMinutes: 2 },
      { id: 'ss-062', recipeId: 'seed-007', stepNumber: 3, instruction: 'Add shrimp in a single layer. Cook 2 minutes per side until pink and curled.', estimatedMinutes: 4 },
      { id: 'ss-063', recipeId: 'seed-007', stepNumber: 4, instruction: 'Squeeze lemon juice over shrimp. Garnish with parsley and serve immediately.', estimatedMinutes: 1 },
    ],
  },
  {
    id: 'seed-008',
    userId: null,
    title: 'Mediterranean Salad Bowl',
    description: 'Fresh and vibrant salad with cucumbers, tomatoes, feta, and olives.',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80',
    cookTimeMinutes: 5,
    prepTimeMinutes: 10,
    servings: 2,
    difficulty: 'easy' as RecipeDifficulty,
    tags: ['salad', 'vegetarian', 'quick', 'lunch', 'healthy'],
    visibility: 'private',
    source: 'system' as RecipeSource,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    deleted: false,
    ingredients: [
      { id: 'si-070', recipeId: 'seed-008', name: 'Cucumber', normalizedName: 'cucumber', quantity: 1, unit: 'pieces', optional: false, sortOrder: 0 },
      { id: 'si-071', recipeId: 'seed-008', name: 'Tomatoes', normalizedName: 'tomato', quantity: 2, unit: 'pieces', optional: false, sortOrder: 1 },
      { id: 'si-072', recipeId: 'seed-008', name: 'Feta Cheese', normalizedName: 'feta cheese', quantity: 100, unit: 'g', optional: false, sortOrder: 2 },
      { id: 'si-073', recipeId: 'seed-008', name: 'Olives', normalizedName: 'olive', quantity: 80, unit: 'g', optional: false, sortOrder: 3 },
      { id: 'si-074', recipeId: 'seed-008', name: 'Red Onion', normalizedName: 'red onion', quantity: 0.5, unit: 'pieces', optional: false, sortOrder: 4 },
      { id: 'si-075', recipeId: 'seed-008', name: 'Olive Oil', normalizedName: 'olive oil', quantity: 3, unit: 'tbsp', optional: false, sortOrder: 5 },
      { id: 'si-076', recipeId: 'seed-008', name: 'Lemon', normalizedName: 'lemon', quantity: 1, unit: 'pieces', optional: false, sortOrder: 6 },
      { id: 'si-077', recipeId: 'seed-008', name: 'Fresh Oregano', normalizedName: 'oregano', optional: true, sortOrder: 7 },
    ],
    steps: [
      { id: 'ss-070', recipeId: 'seed-008', stepNumber: 1, instruction: 'Dice cucumber and tomatoes into bite-sized pieces. Thinly slice red onion.', estimatedMinutes: 5 },
      { id: 'ss-071', recipeId: 'seed-008', stepNumber: 2, instruction: 'Combine vegetables in a large bowl. Add olives and crumbled feta cheese.', estimatedMinutes: 2 },
      { id: 'ss-072', recipeId: 'seed-008', stepNumber: 3, instruction: 'Whisk olive oil and lemon juice together. Drizzle over salad and toss gently.', estimatedMinutes: 2 },
      { id: 'ss-073', recipeId: 'seed-008', stepNumber: 4, instruction: 'Season with salt, pepper, and oregano. Serve immediately.', estimatedMinutes: 1 },
    ],
  },
];
